# starship.toml

add_newline = false

format = """
$character\
$os$hostname\
$directory\
$cmd_duration
[└─>](bold green) """

right_format = """$all"""

continuation_prompt = '▶▶ '

[character]
success_symbol = "[✔️](bold green)" 
error_symbol = "[✘](bold red)"

# Shows the hostname
[hostname]
ssh_only = false
format = '[$hostname](bold yellow) '
disabled = false
ssh_symbol = " "

[directory]
truncation_length = 0
fish_style_pwd_dir_length = 8
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '
format = '[$path]($style)[$read_only]($read_only_style) '

[time]
disabled = false
time_format = "%r" # Hour:Minute Format
format = '󱑍 $time'

[git_branch]
symbol = " "
format = 'via [$symbol$branch]($style)'
truncation_length = 4
truncation_symbol = '…/'
style = 'bold green'

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold green'
conflicted = '🏳'
up_to_date = ''
untracked = ' '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = ' '
modified = ' '
staged = '[++\($count\)](green)'
renamed = '襁 '
deleted = ' '
